stages:
  - build
  - test
  - analyze
  - evaluate
  - deploy

### BUILD

build-linux-x86-64:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout $CI_COMMIT_REF_NAME
    # version without network injection
    - cargo build -p fosr-cli
    - cargo build -p fosr
    # version without ebpf and with iptables
    # - cargo build --features iptables -p fosr
    # version with ebpf
    # - rustup toolchain install nightly --component rust-src
    # - cargo install cargo-binstall --locked
    # - cargo binstall bpf-linker
    - cargo install cargo-deb
    # - cargo build --features ebpf # version with ebpf only
    # - cargo build --features "iptables,ebpf" --release # version with ebpf + iptables
    - cargo deb -p fosr-cli
    - cargo deb -p fosr
    - mkdir target/x86_64-unknown-linux-gnu
    - mv target/release target/x86_64-unknown-linux-gnu
    - cargo doc -p fosr-lib --no-deps
    - mv target/doc doc
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr-cli
      - target/*/release/fosr
      - target/debian/*.deb
      - doc

.build-linux-crosscompile:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout $CI_COMMIT_REF_NAME
    # - rustup toolchain install nightly --component rust-src
    # - cargo install cargo-binstall --locked
    # - cargo binstall bpf-linker
    - cargo install cargo-deb
    - apt update
    - apt install -y $DEPENDENCIES
    - rustup target add $TARGET
    - cargo build --target=$TARGET --config target.$TARGET.linker=\"$GCC\" -p fosr-cli -r
    - cargo deb --target=$TARGET -p fosr-cli -- --config target.$TARGET.linker=\"$GCC\"
    - if [ $TARGET != "arm-unknown-linux-musleabihf" ]; then cargo build --target=$TARGET --config target.$TARGET.linker=\"$GCC\" -p fosr -r; fi
    - if [ $TARGET != "arm-unknown-linux-musleabihf" ]; then cargo deb --target=$TARGET -p fosr -- --config target.$TARGET.linker=\"$GCC\"; fi
    - if [ $TARGET = "arm-unknown-linux-musleabihf" ]; then cd target/debian; debname=$(ls *.deb); mv $debname rpi_$debname; fi
  parallel:
    matrix:
      - TARGET: aarch64-unknown-linux-gnu # ARM64
        DEPENDENCIES: gcc-aarch64-linux-gnu
        GCC: aarch64-linux-gnu-gcc 
      - TARGET: arm-unknown-linux-gnueabihf # ARM32
        DEPENDENCIES: gcc-arm-linux-gnueabihf
        GCC: arm-linux-gnueabihf-gcc
      - TARGET: i686-unknown-linux-gnu #x86-32
        DEPENDENCIES: gcc-i686-linux-gnu
        GCC: i686-linux-gnu-gcc
      - TARGET: arm-unknown-linux-musleabihf # legacy raspberry pi
        DEPENDENCIES: gcc-arm-linux-gnueabihf
        GCC: arm-linux-gnueabihf-gcc
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr-cli
      - target/*/release/fosr
      - target/debian/*.deb

.build-win-x86:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - apt update
    - apt install -y binutils-mingw-w64-x86-64 gcc-mingw-w64
    - rustup target add $TARGET
    - cargo build --target=$TARGET -p fosr-cli -r
    - cargo build --target=$TARGET -p fosr -r
  parallel:
    matrix:
      - TARGET:
        - x86_64-pc-windows-gnu # x86-64
        - i686-pc-windows-gnu # x86-32
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr-cli.exe
      - target/*/release/fosr.exe

build-wasm32:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - rustup target add wasm32-unknown-unknown
    # pinning the version so it is consistent with the version in Cargo.toml
    - cargo install wasm-bindgen-cli --version 0.2.122
    - cargo build -p fosr -r --target wasm32-unknown-unknown --no-default-features --features web
    - wasm-bindgen --out-dir public --target web target/wasm32-unknown-unknown/release/fosr.wasm --no-typescript
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    expire_in: 3 days
    paths:
      - public/fosr.js
      - public/fosr_bg.wasm

### TEST

test-audit:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - cargo install cargo-audit
    - cargo audit -D unsound -D yanked
  allow_failure: true

test-publish:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - git checkout $CI_COMMIT_REF_NAME
    # - rustup toolchain install nightly --component rust-src
    # - cargo install cargo-binstall --locked
    # - cargo binstall bpf-linker
    - cargo build --release
    - cargo publish --dry-run
  allow_failure: true # it can fail on new version update

.generate:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - mkdir -p data/$DATASET/$DATASET-fosr
    - cargo run -- augment-dataset -o data/$DATASET/$DATASET-fosr/data.pcap -s 0 -d 1day -t 0 -p fast --tz UTC -m $DATASET
  parallel:
    matrix:
      - DATASET:
        - cupid
        - cicids17
        - dedale
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - data/$DATASET/$DATASET-fosr/data.pcap

tests:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout $CI_COMMIT_REF_NAME
    # test for debug and release
    - cargo test -p fosr-cli -- --nocapture
    - cargo test -r -p fosr-cli -- --nocapture
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - crates/fosr-cli/deterministic-test.pcap # in case of an error
  allow_failure: true

### ANALYZE

.analyze-dataset:
  image: zeek/zeek
  tags:
    - ci.inria.fr
    - fosr
  stage: analyze
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git config lfs.fetchinclude "data/$DATASET"
    - git checkout $CI_COMMIT_REF_NAME
    - apt update
    - apt install -y tshark suricata git-lfs
    - git lfs pull
    # process all the pcaps
    - cd data/$DATASET/$DATASET-fosr
    - ../../pcap-analysis.sh
    - cd ../$DATASET-eval
    - ../../pcap-analysis.sh
    - cd ../$DATASET-reference
    - ../../pcap-analysis.sh
  parallel:
    matrix:
      - DATASET:
        - cupid
        - cicids17
        - dedale
  artifacts:
    expire_in: 3 days
    paths: # do not export the pcap files
      - data/**/*.csv
      - data/**/*.log
      - data/**/*.txt

### EVALUATE

.evaluate-dataset:
  image: python
  tags:
    - ci.inria.fr
    - fosr
  stage: evaluate
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git config lfs.fetchinclude "data/$DATASET"
    - git checkout $CI_COMMIT_REF_NAME
    - apt update
    - apt install -y graphviz git-lfs
    - git lfs pull
    # evaluation
    - cp data/$DATASET/README.md public/$DATASET.md
    - cd evaluation
    - pip install -r requirements.txt
    - python3 ./evaluation.py --eval ../data/$DATASET/$DATASET-eval/ --synthetic ../data/$DATASET/$DATASET-fosr --ref ../data/$DATASET/$DATASET-reference --output $DATASET
    - python3 ./export.py --dataset $DATASET
    # copy the results table
    - cat results-$DATASET.md >> ../public/$DATASET.md
    - echo -e "\n\n# Figures\n\n" >> ../public/$DATASET.md
    - cd $DATASET
    # copy all experiments images
    - ls *.png | while read file; do echo -e "## ${file/%'.png'}\n\n<center><img style='max-width:100%; width:auto' src='$DATASET/$file'></center>\n" >> ../../public/$DATASET.md; done
    - cd ..
    - mv $DATASET ../public
    # prepare model descriptions to public/
    # copy the automata
    - cd ../crates/fosr-lib/default_models/$DATASET/automata
    - sed -i 's/ N(.*"/"/g' * # to make the automata more readable
    - echo -e "\n\n# Automata\n\n" >> ../../../../../public/$DATASET.md
    - ls *.dot | while read file; do dot -Tpng $file -o ../../../../../public/$DATASET/$file.png -Gdip=150; echo -e "## ${file/%'.dot'}\n\n<center><img style='max-width:100%; width:auto' src='$DATASET/$file.png'></center>\n" >> ../../../../../public/$DATASET.md; done
    - cd ../../../../..
    # copy the BN
    - cp crates/fosr-lib/default_models/$DATASET/bn/bn.png public/$DATASET/bn.png
    - echo -e "# Bayesian network\n\n<center><img style='max-width:100%; width:auto' src='$DATASET/bn.png'></center>\n" >> public/$DATASET.md
  parallel:
    matrix:
      - DATASET:
        - cupid
        - cicids17
        - dedale
  artifacts:
    expire_in: 3 days
    paths:
      - public/$DATASET.md
      - public/$DATASET/

# DEPLOY

pages:
  image: debian:bookworm # required to run fosr
  tags:
    - ci.inria.fr
    - small
  stage: deploy
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - apt update
    - apt install -y pandoc git
    - git checkout $CI_COMMIT_REF_NAME
    - mv doc public/
    - mv target public/bin
    - cat CHANGELOG.md >> public/changelog.md
    - cd public
    # update the build number
    - echo -e "\nBuild version $CI_COMMIT_SHORT_SHA, compiled on $(date -I) ([changelog](changelog.html)).\n" >> intro.md
    - chmod +x ./bin/x86_64-unknown-linux-gnu/release/fosr-cli
    # add the --help output
    - ./bin/x86_64-unknown-linux-gnu/release/fosr-cli create-pcap --help >> howto-create-pcap.md
    - echo "\`\`\`" >> howto-create-pcap.md
    - ./bin/x86_64-unknown-linux-gnu/release/fosr-cli augment-dataset --help >> howto-pcap.md
    - echo "\`\`\`" >> howto-pcap.md
    # - ./bin/x86_64-unknown-linux-gnu/release/fosr inject --help >> howto-inject.md
    # - echo "\`\`\`" >> howto-inject.md
    - ./bin/x86_64-unknown-linux-gnu/release/fosr-cli untaint --help >> howto-untaint.md
    - ./bin/x86_64-unknown-linux-gnu/release/fosr-cli split-untaint --help >> howto-split-untaint.md
    - echo "\`\`\`" >> howto-untaint.md
    # update the deb file paths
    - sed -i -e "s/FOSR_VERSION/$(./bin/x86_64-unknown-linux-gnu/release/fosr-cli -V | cut -d" " -f 2)/g" compile.md
    - pandoc intro.md compile.md howto-create-pcap.md howto-pcap.md howto-untaint.md howto-split-untaint config_doc.md other_software.md schema.md lib.md usecases.md limitations.md refs.md footer.md -o index.html --template template.html --include-after-body footer.html --standalone --toc --toc-depth 1
    - touch cupid.md cicids17.md dedale.md
    - pandoc changelog.md -o changelog.html --template template.html --include-after-body footer.html --standalone --toc
    - pandoc cupid.md -o cupid.html --template template.html --include-after-body footer.html --standalone --toc --toc-depth 1
    - pandoc cicids17.md -o cicids17.html --template template.html --include-after-body footer.html --standalone --toc --toc-depth 1
    - pandoc dedale.md -o dedale.html --template template.html --include-after-body footer.html --standalone --toc --toc-depth 1
    - rm *.md
  artifacts:
    expire_in: 3 days
    paths:
      - public
