stages:
  - build
  - test
  - analyze
  - evaluate
  - deploy

### BUILD

build-linux-x86-64:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    # version without network injection
    - cargo build -p fosr
    # version without ebpf and with iptables
    # - cargo build --features iptables -p fosr
    # version with ebpf
    - rustup toolchain install nightly --component rust-src
    - cargo install bpf-linker
    - cargo install cargo-deb
    # - cargo build --features ebpf # version with ebpf only
    # - cargo build --features "iptables,ebpf" --release # version with ebpf + iptables
    - cargo deb -p fosr
    - mkdir target/x86_64-unknown-linux-gnu
    - mv target/release target/x86_64-unknown-linux-gnu
    - cargo doc
    - mv target/doc doc
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr
      - target/debian/*.deb
      - doc

build-linux-x86-32:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    - cargo install cargo-deb
    - apt update
    - apt install -y gcc-i686-linux-gnu
    - rustup target add i686-unknown-linux-gnu
    # Aya doesn’t compile for some reason
    - cargo build --target=i686-unknown-linux-gnu --config target.i686-unknown-linux-gnu.linker=\"i686-linux-gnu-gcc\" -p fosr -r
    - cargo deb --target=i686-unknown-linux-gnu -p fosr -- --config target.i686-unknown-linux-gnu.linker=\"i686-linux-gnu-gcc\"
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr
      - target/debian/*.deb

build-linux-legacy-raspberry-pi:
  # a build targeting old rapsberry pi with armv6 processors
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    - cargo install cargo-deb
    - apt update
    - apt install -y gcc-arm-linux-gnueabihf
    - rustup target add arm-unknown-linux-musleabihf
    - cargo build --target=arm-unknown-linux-musleabihf --config target.arm-unknown-linux-musleabihf.linker=\"arm-linux-gnueabihf-gcc\" -p fosr -r
    - cargo deb --target=arm-unknown-linux-musleabihf -p fosr -- --config target.arm-unknown-linux-musleabihf.linker=\"arm-linux-gnueabihf-gcc\"
    - cd target/debian
    - debname=$(ls *.deb)
    - mv $debname rpi_$debname
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr
      - target/debian/*.deb

build-linux-arm-32:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    - rustup toolchain install nightly --component rust-src
    - cargo install bpf-linker
    - cargo install cargo-deb
    - apt update
    - apt install -y gcc-arm-linux-gnueabihf
    - rustup target add arm-unknown-linux-gnueabihf
    - cargo build --target=arm-unknown-linux-gnueabihf --config target.arm-unknown-linux-gnueabihf.linker=\"arm-linux-gnueabihf-gcc\" -p fosr -r
    - cargo deb --target=arm-unknown-linux-gnueabihf -p fosr -- --config target.arm-unknown-linux-gnueabihf.linker=\"arm-linux-gnueabihf-gcc\"
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr
      - target/debian/*.deb

build-linux-arm-64:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    - rustup toolchain install nightly --component rust-src
    - cargo install bpf-linker
    - cargo install cargo-deb
    - apt update
    - apt install -y gcc-aarch64-linux-gnu
    - rustup target add aarch64-unknown-linux-gnu
    - cargo build --target=aarch64-unknown-linux-gnu --config target.aarch64-unknown-linux-gnu.linker=\"aarch64-linux-gnu-gcc\" -p fosr -r
    - cargo deb --target=aarch64-unknown-linux-gnu -p fosr -- --config target.aarch64-unknown-linux-gnu.linker=\"aarch64-linux-gnu-gcc\"
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr
      - target/debian/*.deb

build-win64-x86:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    - apt update
    - apt install -y binutils-mingw-w64-x86-64 gcc-mingw-w64
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --target=x86_64-pc-windows-gnu -p fosr -r
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr.exe

build-win32-x86:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    - apt update
    - apt install -y binutils-mingw-w64-x86-64 gcc-mingw-w64
    - rustup target add i686-pc-windows-gnu
    - cargo build --target=i686-pc-windows-gnu -p fosr -r
  artifacts:
    expire_in: 3 days
    paths:
      - target/*/release/fosr.exe

build-wasm32:
  tags:
    - ci.inria.fr
    - large
  stage: build
  image: rust
  script:
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-bindgen-cli
    - cargo build -p fosr-gui -r --target wasm32-unknown-unknown --no-default-features --features models
    - wasm-bindgen --out-dir public --target web target/wasm32-unknown-unknown/release/fosr_gui.wasm --no-typescript
  artifacts:
    expire_in: 3 days
    paths:
      - public/fosr_gui.js
      - public/fosr_gui_bg.wasm

### TEST

test-audit:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  script:
    - cargo install cargo-audit
    - cargo audit -D unsound -D yanked
  allow_failure: true

test-publish:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  script:
    - rustup toolchain install nightly --component rust-src
    - cargo install bpf-linker
    - cargo build --release
    - cargo publish --dry-run
  allow_failure: true # it can fail on new version update

generate:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  script:
    - mkdir -p data/cupid/cupid-fosr
    - cargo run -- augment-dataset -o data/cupid/cupid-fosr/data.pcap -s 0 -d 1day -t 0 -p fast --tz CET -m cupid
    - mkdir -p data/cicids17/cicids17-fosr
    - cargo run -- augment-dataset -o data/cicids17/cicids17-fosr/data.pcap -s 0 -d 1day -t 0 -p fast --tz CET -m cicids17
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - data/

tests:
  tags:
    - ci.inria.fr
    - large
  stage: test
  image: rust
  script:
    - cargo test -p fosr -- --nocapture
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - crates/fosr/deterministic-test.pcap # in case of an error
  allow_failure: true

### ANALYZE

analysis-cupid:
  image: zeek/zeek
  tags:
    - ci.inria.fr
    - small
  stage: analyze
  script:
    - apt update
    - apt install -y tshark suricata
    - cd data/cupid/cupid-fosr
    - ../../pcap-analysis.sh
    - suricata -c /etc/suricata/suricata.yaml -r data.pcap > suricata.txt
  artifacts:
    expire_in: 3 days
    paths:
      - data/cupid/cupid-fosr

analysis-cicids17:
  image: zeek/zeek
  tags:
    - ci.inria.fr
    - small
  stage: analyze
  script:
    - apt update
    - apt install -y tshark suricata
    - cd data/cicids17/cicids17-fosr
    - ../../pcap-analysis.sh
    - suricata -c /etc/suricata/suricata.yaml -r data.pcap > suricata.txt
  artifacts:
    expire_in: 3 days
    paths:
      - data/cicids17/cicids17-fosr

### EVALUATE

evaluate-cupid:
  image: python
  tags:
    - ci.inria.fr
    - small
  stage: evaluate
  script:
    - apt update
    - apt install graphviz graphviz-tools
    - mkdir public/cupid
    # evaluation
    - cd evaluation
    - pip install -r requirements.txt
    - python3 ./evaluation.py --eval ../data/cupid/cupid-eval/ --synthetic ../data/cupid/cupid-fosr --ref ../data/cupid/cupid-reference --output cupid
    - python3 ./export.py --dataset cupid
    - echo results-cupid.md >> public/dataset-cupid.md
    # prepare model descriptions to public/
    - cd crates/fosr-lib/default_models/cupid/automata
    - sed -i 's/ N(.*"/"/g' * # to make the automata more readable
    - echo -e "## Automata\n\n" >> ../../../../../public/dataset-cupid.md
    - ls *.dot | while read file; do dot -Tpng $file -o ../../../../../public/cupid/$file.png -Gdip=150; echo -e "### ${file/%'.dot'}\n\n<center><img style='max-width:100%; width:auto' src='cupid/$file.png'></center>\n" >> ../../../../../public/dataset-cupid.md; done
    - cd ../../../../..
    - cp crates/fosr-lib/default_models/cupid/bn/bn_common.png public/cupid/bn.png
    - echo -e "## Bayesian network\n\n<center><img style='max-width:100%; width:auto' src='cupid/bn.png'></center>\n" >> public/dataset-cupid.md
    - mv public/dataset-cupid.md public/cupid.md
  artifacts:
    expire_in: 3 days
    paths:
      - public/cupid.md
      - public/cupid/

.cicids17-dataset:
  image: alpine
  tags:
    - ci.inria.fr
    - small
  stage: evaluate
  script:
    - apk add graphviz
    - mkdir public/cicids17
    - cd crates/fosr-lib/default_models/cicids17/automata
    - ls *.dot | while read file; do dot -Tpng $file -o ../../../../../public/cicids17/$file.png -Gdip=150; echo - \[$file\]\(cicids17/$file.png\) >> ../../../../../public/dataset-cicids17.md; done
    - cd ../../../../..
    - cp crates/fosr-lib/default_models/cicids17/bn/bn_common.png public/cicids17/bn.png
    - echo -e "\n## Bayesian network\n![](cicids17/bn.png)" >> public/dataset-cicids17.md
    - mv public/dataset-cicids17.md public/cicids17.md
    # TODO: add evaluation
  artifacts:
    expire_in: 3 days
    paths:
      - public/cicids17.md
      - public/cicids17/

# DEPLOY

pages:
  image: debian:bookworm # required to run fosr
  tags:
    - ci.inria.fr
    - small
  stage: deploy
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - apt update
    - apt install -y pandoc
    - mv doc public/
    - mv target public/bin
    - mv *.zip public/
    - mv sample.pcap public/
    - cat CHANGELOG.md >> public/changelog.md
    - cd public
    # update the build number
    - echo -e "\nBuild version $CI_COMMIT_SHORT_SHA, compiled on $(date -I) ([changelog](changelog.html)).\n" >> intro.md
    - chmod +x ./bin/x86_64-unknown-linux-gnu/release/fosr
    # add the --help output
    - ./bin/x86_64-unknown-linux-gnu/release/fosr augment-dataset --help >> howto-pcap.md
    - echo "\`\`\`" >> howto-pcap.md
    # - ./bin/x86_64-unknown-linux-gnu/release/fosr inject --help >> howto-inject.md
    # - echo "\`\`\`" >> howto-inject.md
    - ./bin/x86_64-unknown-linux-gnu/release/fosr untaint --help >> howto-untaint.md
    - echo "\`\`\`" >> howto-untaint.md
    # update the deb file paths
    - sed -i -e "s/FOSR_VERSION/$(./bin/x86_64-unknown-linux-gnu/release/fosr -V | cut -d" " -f 2)/g" compile.md
    - pandoc intro.md compile.md howto-pcap.md howto-inject.md howto-untaint.md config_doc.md other_software.md schema.md lib.md roadmap.md usecases.md analysis.md limitations.md refs.md footer.md -o index.html --template template.html --include-after-body footer.html --standalone --toc --toc-depth 1
    - pandoc changelog.md -o changelog.html --template template.html --include-after-body footer.html --standalone --toc
    - pandoc cupid.md -o cupid.html --template template.html --include-after-body footer.html --standalone --toc
    - pandoc cicids17.md -o cicids17.html --template template.html --include-after-body footer.html --standalone --toc
    - rm *.md
  artifacts:
    expire_in: 3 days
    paths:
      - public
