[package]
name = "fosr-cli"
version = "1.0.0-dev"
authors = ["Pierre-François Gimenez <pierre-francois.gimenez@inria.fr>","Dorian Bachelot"]
edition = "2024"
description = "Fos-R (Forger Of Security Records) is an ML-based synthetic network traffic generator."
homepage = "https://fosr.inria.fr"
repository = "https://gitlab.inria.fr/pirat-public/Fos-R"
license = "GPL-3.0"
categories = ["network-programming","security","science"]
keywords = ["cli", "networking", "ai", "security"]

[dependencies]
chrono = "0.4.45"
chrono-tz = "0.10.4"
clap = { version = "4.6.6", features = ["derive"] }
crossbeam-channel = "0.5.16"
ctrlc = "3.5.2"
env_logger = { version = "0.11.11", default-features = false, features = ["auto-color", "humantime"] }
fosr-lib = { version = "1.0.0-dev", path = "../fosr-lib" }
humantime = "2.4.0"
indicatif = "0.18.6"
itertools = "0.14.0"
log = "0.4.34"
num_cpus = "1.17.0"
pcap-file = "2.0.0"
pnet = { version = "0.35.0", default-features = false }
pnet_packet = "0.35.0"
serde_yaml = "0.9.34"
thingbuf = "0.1.6"

[target.'cfg(all(target_os = "linux", any(target_env = "", target_env = "gnu")))'.dependencies]
tikv-jemallocator = "0.6.1"

[dev-dependencies]
assert_cmd = "2.2.2"
hex = "0.4.3"
sha2 = "0.11.0"

[features]
models_cupid = ["fosr-lib/models_cupid"]
models_cicids17 = ["fosr-lib/models_cicids17"]
models_dedale = ["fosr-lib/models_dedale"]
default = ["models_cupid", "models_cicids17", "models_dedale"]
net_injection = ["pnet/std", "fosr-lib/net_injection"]

# Linux only
iptables = ["net_injection", "fosr-lib/iptables"]

# Linux & Windows only
ebpf = ["net_injection", "fosr-lib/ebpf"]

[package.metadata.deb]
section = "science"
depends = ["$auto", "iptables"]
