Vagrant.configure("2") do |config|

  config.vm.define "linux" do |linux|
    linux.vm.box = "generic/debian12"
    linux.vm.hostname = "linux"
    linux.vm.network "private_network", type: "static", ip: "192.168.56.101"
    linux.vm.synced_folder "..", "/home/vagrant/Fos-R", create: true

    linux.vm.provision "ansible" do |ansible|
      ansible.playbook = "./main.yml"
    end
  end

  config.vm.define "windows" do |windows|
    windows.vm.box = "gusztavvargadr/windows-11"
    windows.vm.hostname = "windows"
    windows.vm.network "private_network", type: "static", ip: "192.168.56.102"
    windows.vm.communicator = "winrm"
    windows.ssh.shell = "powershell.exe"
    windows.winssh.shell = "powershell"
    windows.vm.synced_folder "..", "C:\\Users\\Vagrant\\Fos-R", create: true

    windows.vm.provision "ansible" do |ansible|
      ansible.playbook = "./main.yml"
      ansible.extra_vars = {
        ansible_winrm_scheme: 'http'
      }
    end
  end
end

