[package]
name = "fosr-lib"
version = "1.0.0-dev"
authors = ["Pierre-François Gimenez <pierre-francois.gimenez@inria.fr>","Dorian Bachelot","Florentin Labelle","Evan Morin"]
edition = "2024"
description = "The library of Fos-R (Forger Of Security Records), the ML-based synthetic network traffic generator."
homepage = "https://fosr.inria.fr"
repository = "https://gitlab.inria.fr/pirat-public/Fos-R"
license = "GPL-3.0"
rust-version = "1.85.1"
categories = ["network-programming","security","science"]
keywords = ["networking", "ai", "security"]

[dependencies]
base64 = "0.22.1"
chrono = "0.4.45"
crossbeam-channel = "0.5.16"
derivative = "2.2.0"
fosr-ebpf = { version = "0.1.1", path = "../fosr-ebpf", optional = true }
include-bytes-zstd = "0.1.0"
include_dir = { version = "0.7.4", features = ["glob"] }
indicatif = "0.18.6"
log = "0.4.34"
log-once = "0.4.1"
microlp = "0.6"
nalgebra = "0.35"
pcap-file = "2.0.0"
pnet = { version = "0.35.0", default-features = false }
pnet_packet = "0.35.0"
rand = "0.10.0"
rand_core = "0.10.0"
rand_distr = "0.6.0"
rand_pcg = "0.10.0"
serde = { version = "1.0.229", features = ["derive"] }
serde-xml-rs = "0.8.2"
serde_json = "1.0"
serde_yaml = "0.9.34"
statrs = "0.19.1"
strum = { version = "0.28.0", features = ["derive"] }
thingbuf = "0.1.6"

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
aya = { version = "0.13.1", default-features = false, optional = true }

[features]
default = []
net_injection = ["pnet/std"]
models_cupid = []
models_cicids17 = []
models_dedale = []

# Linux only
iptables = ["net_injection"]

# Linux & Windows only
ebpf = ["dep:aya", "net_injection", "dep:fosr-ebpf"]

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.build-dependencies]
anyhow = { version = "1", default-features = false, optional = true }
aya-build = { version = "0.1.2", default-features = false, optional = true }
fosr-ebpf = { path = "../fosr-ebpf", optional = true }

# auto-detect WASM target and add the feature to getrandom
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4.3", features=["wasm_js"] }
