[[hosts]]
    [[hosts.interfaces]]
        name = "barrel"
        ip = "10.25.100.10"
        provides = []
        uses = [465]
[[hosts]]
    [[hosts.interfaces]]
        name = "cabin1"
        ip = "10.25.100.11"
        provides = []
        uses = [1883]
[[hosts]]
    [[hosts.interfaces]]
        name = "cabin2"
        ip = "10.25.100.12"
        provides = []
        uses = [1883,443,80]
[[hosts]]
    [[hosts.interfaces]]
        name = "cabin3"
        ip = "10.25.100.13"
        provides = []
        uses = [1883,443,80]
[[hosts]]
    [[hosts.interfaces]]
        name = "quarters"
        ip = "10.25.100.14"
        provides = [1883,443,80,465]
        uses = []
