[[hosts]]
    [[hosts.interfaces]]
        ip = "10.25.100.11"
        provides = [80, 21, 443, 465]
        uses = [53,22]
[[hosts]]
    [[hosts.interfaces]]
        ip = "10.25.100.12"
        provides = [53, 1883]
        uses = [465]
[[hosts]]
    [[hosts.interfaces]]
        ip = "10.25.100.13"
        provides = [22]
        uses = [21, 443, 1883]
[[hosts]]
    [[hosts.interfaces]]
        ip = "10.25.100.20"
        uses = [22, 21, 443, 1883]
