[package]
name = "fosr"
authors = ["Pierre-François Gimenez"]
version = "0.1.0"
edition = "2021"
description = "FosR (Forgery of security Recordings) is a synthetic pcap generator. This Rust project is only used for the generation itself but relies on models learned with software available on our GitHub."
homepage = "https://pfgimenez.fr/fosr"
repository = "https://github.com/FosR-project/FosR"
license = "GPL-3.0"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
crossbeam-channel = "0.5.13"
hex = "0.4.3"
pnet_packet = "0.35.0"
pcap = "2.2.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rand_pcg = "0.3.1"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0"
libc = "0.2.162"
