[[hosts]]
    [[hosts.interfaces]]
        ip = "192.168.0.1"
        provides = [80, 21, 443, 465, 1883]
        uses = [80, 21, 443, 465, 1883]
        mac = "28:00:af:37:a9:cd"
[[hosts]]
    [[hosts.interfaces]]
        ip = "192.168.0.2"
        provides = [80, 21, 443, 465, 1883]
        uses = [80, 21, 443, 465, 1883]
        mac = "cc:48:3a:a5:ef:12" 
