[[hosts]]
    [[hosts.interfaces]]
        ip = "192.168.1.59"
        provides = [80, 21, 443, 465, 1883]
[[hosts]]
    [[hosts.interfaces]]
        ip = "192.168.1.36"
        uses = [80, 21, 443, 465, 1883]
