[[hosts]]
    [[hosts.interfaces]]
        ip = "192.168.0.1"
        provides = [80, 21, 443, 465, 1883]
        uses = [80, 21, 443, 465, 1883]
[[hosts]]
    [[hosts.interfaces]]
        ip = "192.168.0.2"
        provides = [80, 21, 443, 465, 1883]
        uses = [80, 21, 443, 465, 1883]
